### ISSUE TITLE
i am getting this error on heroku

### ISSUE THREAD

**Issue by telegrambotdev** [mezgoodle/weather-bot#53]
i put the correct values in .env file and deployed on heroku.but i am getting some errors,screenshots are attaching

![IMG_20200828_192317_022](https://user-images.githubusercontent.com/20116017/91571454-fb937300-e963-11ea-9145-a1c4ef68ae96.jpg)
![IMG_20200828_192322_143](https://user-images.githubusercontent.com/20116017/91571564-01895400-e964-11ea-8a46-a0b76f179a4b.jpg)

**Comment by telegrambotdev** [comment]
Showing mongonetwork error.does we need our own mongo database ?

**Comment by mezgoodle** [comment]
I am using [MongoDB Atlas](https://www.mongodb.com/cloud/atlas)
Also look at this [line](https://github.com/mezgoodle/weather-bot/blob/master/config.js#L11) in `config.js`, replace `mezgoodle` to `your-nickname` or just copy **dbURI** from MongoDB Atlas
